version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=swgraphql"
      - "POSTGRES_DB=swgraphql"
      - "POSTGRES_PASSWORD=swgraphql"
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  cache:
    driver: local